-- ============================================================
-- V1: users テーブル（認証・権限管理の基盤）
-- 既存の Hibernate 自動生成から Flyway 管理へ移行
-- ============================================================

CREATE TABLE users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'STAFF', 'CUSTOMER'))
);

COMMENT ON TABLE  users IS 'ユーザー（認証・権限管理）';
COMMENT ON COLUMN users.role IS 'ADMIN / STAFF / CUSTOMER';
