-- ============================================================
-- V2: 予約ドメイン（店舗・スタッフ・サービス・予約）
-- ============================================================

-- 店舗
CREATE TABLE stores (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    address       VARCHAR(255),
    phone         VARCHAR(20),
    opening_time  TIME         NOT NULL,
    closing_time  TIME         NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT chk_stores_hours CHECK (opening_time < closing_time)
);

-- 店舗×スタッフ（多対多。STAFFの「自店のみ操作」制御に使用）
CREATE TABLE store_staff (
    id          BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id    BIGINT     NOT NULL,
    user_id     BIGINT     NOT NULL,
    created_at  TIMESTAMP  NOT NULL,
    CONSTRAINT fk_store_staff_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_store_staff_user  FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT uq_store_staff UNIQUE (store_id, user_id)
);

-- サービス／メニュー（所要時間で予約終了時刻を算出）
CREATE TABLE services (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id          BIGINT       NOT NULL,
    name              VARCHAR(100) NOT NULL,
    duration_minutes  INT          NOT NULL,
    price             INT          NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    CONSTRAINT fk_services_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT chk_services_duration CHECK (duration_minutes > 0),
    CONSTRAINT chk_services_price    CHECK (price >= 0)
);

-- 予約
CREATE TABLE reservations (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     BIGINT      NOT NULL,
    service_id   BIGINT      NOT NULL,
    customer_id  BIGINT      NOT NULL,
    staff_id     BIGINT      NOT NULL,
    start_time   TIMESTAMP   NOT NULL,
    end_time     TIMESTAMP   NOT NULL,
    status       VARCHAR(20) NOT NULL,
    note         VARCHAR(500),
    created_at   TIMESTAMP   NOT NULL,
    updated_at   TIMESTAMP   NOT NULL,
    CONSTRAINT fk_reservations_store    FOREIGN KEY (store_id)    REFERENCES stores(id),
    CONSTRAINT fk_reservations_service  FOREIGN KEY (service_id)  REFERENCES services(id),
    CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES users(id),
    CONSTRAINT fk_reservations_staff    FOREIGN KEY (staff_id)    REFERENCES users(id),
    CONSTRAINT chk_reservations_time   CHECK (start_time < end_time),
    CONSTRAINT chk_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'))
);

-- よく使う検索のためのインデックス
CREATE INDEX idx_reservations_store    ON reservations(store_id);
CREATE INDEX idx_reservations_customer ON reservations(customer_id);
CREATE INDEX idx_reservations_staff    ON reservations(staff_id);

COMMENT ON TABLE stores       IS '店舗';
COMMENT ON TABLE store_staff  IS '店舗とスタッフの紐付け（多対多）';
COMMENT ON TABLE services     IS 'サービス／メニュー';
COMMENT ON TABLE reservations IS '予約';
